version: '3.7'

services:
  server:
    image: postgres:15.1
    container_name: server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psql_db
    ports:
      - 5432:5432
    volumes:
      - $PWD/tmp/pgdata:/var/lib/postgresql/data
    networks:
      - local

  devops:
    image: dpage/pgadmin4:6.18
    container_name: devops
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      server:
        condition: service_started
    networks:
      - local
      
networks:
  local:
    name: $NETWORK