version: '3.7'

services:

  defaultserver:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: defaultserver
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - $PWD/tmp/mysql:/var/lib/mysql
    networks:
      - local

  adminer:
    image: adminer:4.8.1
    # restart: always
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      defaultserver:
        condition: service_started
    networks:
      - local

networks:
  local:
    name: $NETWORK